[WIP] Add support for AWS IAM authentication
logstash-plugins/logstash-integration-kafka pull request #126
Opened 2022-09-07 08:14 UTC by korsosa

AWS MSK has an optional IAM auth feature that enables to use AWS IAM policies for managing authentication/authorization to Kafka resources instead of Kafka ACLs. More information in [the AWS MSK documentation](https://docs.aws.amazon.com/msk/latest/developerguide/iam-access-control.html). 

This change includes the [AWS library for MSK IAM auth](https://github.com/aws/aws-msk-iam-auth) that provides a new SASL mechanism `AWS_MSK_IAM`.

In previous plugin versions the transitive Jar dependencies were not exported. The AWS MSK IAM auth library is a jar without dependencies, this caused issues with finding various AWS classes. Instead of listing all the transitive AWS dependencies, this change also modifies `build.gradle` to export all Jar dependencies and add them to the jars file. If a transitive dependency should not be exported, the `transitive=false` flag can be used.

Usage as input/output:
```
 kafka {
    topic_id => "yourtopic"
    bootstrap_servers => "yourbroker"
    security_protocol => "SASL_SSL"
    sasl_mechanism => "AWS_MSK_IAM"
    sasl_jaas_config => "software.amazon.msk.auth.iam.IAMLoginModule required;"
  }
```

2022-09-09 13:18 UTC, korsosa commented
Hey @roaksoax , could you please review this PR or is there anything I can do to help release it? :)

2022-09-09 13:26 UTC, korsosa commented
Hey @andsel & @jsvd, could you please review this PR? Is there anything I can do to help review/merge it? :)

2023-01-24 13:44 UTC, otavioprado commented
Hey @andsel & @jsvd, any idea when this PR will be merged?

2023-05-16 15:46 UTC, denes16 commented
Any news on this?

2023-09-21 04:30 UTC, mvignes89 commented
Any update on this ?

2024-01-05 10:28 UTC, korsosa commented
Hey @andsel, is there anything I can do to get this merged? I'd be happy to resolve the conflicts and update the PR but not sure if there's any intention from your side to merge it. Unfortunately, I haven't received any feedback since I opened the PR, although I believe this would be a useful addition to the plugin.

2024-01-24 09:28 UTC, andsel requested changes
Hi @korsosa 
the PR seem promising, however would be better to split in 2:
- the first PR would introduce just the setting `sasl.client.callback.handler.class`, which is the abstract way to provide any SASL client handler
- another one for the specific dependencies related to AWS AIM

2025-05-02 20:59 UTC, amiraminb commented
Hi @korsosa, Do we have any estimation on when this feature will be merged?

2025-05-05 08:08 UTC, andsel commented
This PR can be closed because split in:
- #177 (merged)
- #178 (waiting to release the uber jar to be referenced by the code in the PR)

2025-05-08 13:53 UTC, closed without merging